# Generated by Django 5.1.1 on 2024-09-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
